version: "3"

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data_container:/data/redis

volumes:
    redis_data_container:
        driver: local
